gui:
  nerdFontsVersion: "3"
  scrollHeight: 2
  showFileTree: false
  # showRootItemInFileTree: false
# git:
#   paging:
#     colorArg: always
#     pager: delta --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
